### ISSUE TITLE
Problem executing Getting started example

### ISSUE THREAD

**Issue by PatWalters** [molML/MoleculeACE#2]
Hi,

I was trying to run the first "Getting started" example in README.md and I ran into a problem executing the line

model = algorithm(hyperparameters)

It looks like the hyperparameters are not compatible. 

Thanks in advance for your help

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 algorithm(hyperparameters)

File ~/anaconda3/envs/moleculeACE/lib/python3.8/site-packages/MoleculeACE/models/mpnn.py:28, in MPNN.__init__(self, node_in_feats, node_hidden, edge_in_feats, edge_hidden, message_steps, dropout, transformer_heads, transformer_hidden, seed, fc_hidden, n_fc_layers, lr, epochs, *args, **kwargs)
     22 def __init__(self, node_in_feats: int = 37, node_hidden: int = 64, edge_in_feats: int = 6,
     23              edge_hidden: int = 128, message_steps: int = 3, dropout: float = 0.2,
     24              transformer_heads: int = 8, transformer_hidden: int = 128, seed: int = RANDOM_SEED,
     25              fc_hidden: int = 64, n_fc_layers: int = 1, lr: float = 0.0005, epochs: int = 300, *args, **kwargs):
     26     super().__init__()
---> 28     self.model = MPNNmodel(node_in_feats=node_in_feats, node_hidden=node_hidden, edge_in_feats=edge_in_feats,
     29                            edge_hidden=edge_hidden, message_steps=message_steps, dropout=dropout,
     30                            transformer_heads=transformer_heads, transformer_hidden=transformer_hidden, seed=seed,
     31                            fc_hidden=fc_hidden, n_fc_layers=n_fc_layers)
     33     self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
     34     self.loss_fn = torch.nn.MSELoss()

File ~/anaconda3/envs/moleculeACE/lib/python3.8/site-packages/MoleculeACE/models/mpnn.py:62, in MPNNmodel.__init__(self, node_in_feats, node_hidden, edge_in_feats, edge_hidden, message_steps, dropout, transformer_heads, transformer_hidden, seed, fc_hidden, n_fc_layers, *args, **kwargs)
     59 self.node_in_feats = node_in_feats
     61 # Layer to project node features to hidden features
---> 62 self.project_node_feats = Sequential(Linear(node_in_feats, node_hidden), ReLU())
     64 # The 'learnable message function'
     65 edge_network = Sequential(Linear(edge_in_feats, edge_hidden), ReLU(),
     66                           Linear(edge_hidden, node_hidden * node_hidden))

File ~/anaconda3/envs/moleculeACE/lib/python3.8/site-packages/torch/nn/modules/linear.py:96, in Linear.__init__(self, in_features, out_features, bias, device, dtype)
     94 self.in_features = in_features
     95 self.out_features = out_features
---> 96 self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
     97 if bias:
     98     self.bias = Parameter(torch.empty(out_features, **factory_kwargs))

TypeError: empty(): argument 'size' must be tuple of SymInts, but found element of type dict at pos 2

```

**Comment by pkiruba** [comment]
Hi, 

I also try to run the "Getting started" example and end up with a similar error to what @PatWalters pointed out.

I used the same versions of the libraries mentioned in the "Installation" section.

```
model = algorithm(hyperparameters)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kirupa/miniconda3/envs/MoleculeACE/lib/python3.8/site-packages/MoleculeACE/models/mpnn.py", line 28, in __init__
    self.model = MPNNmodel(node_in_feats=node_in_feats, node_hidden=node_hidden, edge_in_feats=edge_in_feats,
  File "/home/kirupa/miniconda3/envs/MoleculeACE/lib/python3.8/site-packages/MoleculeACE/models/mpnn.py", line 62, in __init__
    self.project_node_feats = Sequential(Linear(node_in_feats, node_hidden), ReLU())
  File "/home/kirupa/miniconda3/envs/MoleculeACE/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 85, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
TypeError: empty(): argument 'size' must be tuple of ints, but found element of type dict at pos 2
```
Looking forward for your help.

Thanks,
Kiruba

**Comment by derekvantilborg** [comment]
Thanks! I will resolve it ASAP

**Comment by derekvantilborg** [comment]
Instead of `model = algorithm(hyperparameters)` it should be `model = algorithm(**hyperparameters)`. I updated the readme, my bad.
